services:
  problem-service:
    build:
      context: ./problem_service
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - DB_URI=mongodb://mongo:27017/leetcode_problem_service
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - backend

  submission-service:
    build:
      context: ./submission_service
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    environment:
      - PORT=3002
      - DB_URI=mongodb://mongo:27017/leetcode_submission_service
      - PROBLEM_SERVICE_URL=http://problem-service:3001/api/v1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend

  evaluation-service:
    build:
      context: ./evaluation_service
      dockerfile: Dockerfile
    ports:
      - 3003:3003
    environment:
      - PORT=3003
      - PROBLEM_SERVICE_URL=http://problem-service:3001/api/v1
      - SUBMISSION_SERVICE_URL=http://submission-service:3002/api/v1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DOCKER_HOST=tcp://dind:2375
    depends_on:
      redis:
        condition: service_healthy
      dind:
        condition: service_healthy
    networks:
      - backend

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - backend

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - backend

  # docker inside docker
  # privileged: true is required for Docker-in-Docker (DinD) because the inner Docker daemon (dockerd) needs
  # low-level kernel capabilities that normal containers do not have.
  dind:
    image: docker:24-dind
    restart: always
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    healthcheck:
      test: ["CMD", "docker", "info"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - backend

networks:
  backend:
    driver: bridge
