services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    # ports:
    #   - 27017:27017
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - mongo_db_network
    volumes:
      - leetcode_mongo_data:/data/db

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    # ports:
    #   - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - redis_network
    volumes:
      - redis_data:/data
  
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # ports:
    #   - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postgres_db_network
    
  migrate:
    build:
      context: ./auth_service
      dockerfile: Dockerfile.migrate
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=auth_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_ACCESS_SECRET=local-access-secret-change-in-prod
      - JWT_REFRESH_SECRET=local-refresh-secret-change-in-prod
    depends_on:
      postgres:
        condition: service_healthy
    restart: on-failure
    networks:
      - postgres_db_network

  # docker inside docker
  # privileged: true is required for Docker-in-Docker (DinD) because the inner Docker daemon (dockerd) needs
  # low-level kernel capabilities that normal containers do not have.
  dind:
    image: docker:24-dind
    restart: always
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
    healthcheck:
      test: ["CMD", "docker", "info"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - execution

  api-gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - PORT=3000
      - NODE_ENV=production
      - SERVICE_NAME=api-gateway
      - REGISTRY_SERVICE_URL=http://registry-service:3001/api/v1
      - REGISTRY_HMAC_SHARED_SECRET=kfsKE(@#*oweiKOQWID23984
      - API_GATEWAY_HMAC_SHARED_SECRET=3049sKKJDIWEO2983023909234
    networks:
      - backend

  registry-service:
    build:
      context: ./registry_service
      dockerfile: Dockerfile.dev
    # ports:
    #   - 3001:3001
    restart: unless-stopped
    environment:
      - PORT=3001
      - NODE_ENV=production
      - SERVICE_NAME=registry-service
      - REGISTRY_HMAC_SHARED_SECRET=kfsKE(@#*oweiKOQWID23984
    networks:
      - backend


  problem-service:
    build:
      context: ./problem_service
      dockerfile: Dockerfile
    # ports:
    #   - 3010:3010
    restart: unless-stopped
    environment:
      - PORT=3010
      - DB_URI=mongodb://mongo:27017/leetcode_problem_service
      - NODE_ENV=production
      - SERVICE_NAME=problem-service
      - REGISTRY_SERVICE_URL=http://registry-service:3001/api/v1
      - REGISTRY_HMAC_SHARED_SECRET=kfsKE(@#*oweiKOQWID23984
      - API_GATEWAY_HMAC_SHARED_SECRET=3049sKKJDIWEO2983023909234
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - backend
      - mongo_db_network

  submission-service:
    build:
      context: ./submission_service
      dockerfile: Dockerfile
    deploy:
      replicas: 2
    ports:
      - 3020-3021:3020
    # ports:
    #   - 3020:3020
    restart: unless-stopped
    environment:
      - PORT=3020
      - DB_URI=mongodb://mongo:27017/leetcode_submission_service
      - PROBLEM_SERVICE_URL=http://problem-service:3010/api/v1
      - REGISTRY_SERVICE_URL=http://registry-service:3001/api/v1
      - REDIS_URL=redis://redis:6379
      - SERVICE_NAME=submission-service
      - NODE_ENV=production
      - EVALUATION_JOB_NAME=evaluate-submission
      - SUBMISSION_QUEUE_NAME=submission_queue
      - STATUS_UPDATE_QUEUE_NAME=status_update_queue
      - STATUS_UPDATE_JOB_NAME=update-submission-status
      - REGISTRY_HMAC_SHARED_SECRET=kfsKE(@#*oweiKOQWID23984
      - API_GATEWAY_HMAC_SHARED_SECRET=3049sKKJDIWEO2983023909234
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
      - mongo_db_network
      - redis_network

  evaluation-service:
    build:
      context: ./evaluation_service
      dockerfile: Dockerfile
    # ports:
    #   - 3030:3030
    restart: unless-stopped
    environment:
      - PORT=3030
      - PROBLEM_SERVICE_URL=http://problem-service:3010/api/v1
      - SUBMISSION_SERVICE_URL=http://submission-service:3020/api/v1
      - REGISTRY_SERVICE_URL=http://registry-service:3001/api/v1
      - REDIS_URL=redis://redis:6379
      - DOCKER_HOST=tcp://dind:2375
      - SERVICE_NAME=evaluation-service
      - EVALUATION_JOB_NAME=evaluate-submission
      - SUBMISSION_QUEUE_NAME=submission_queue
      - STATUS_UPDATE_QUEUE_NAME=status_update_queue
      - STATUS_UPDATE_JOB_NAME=update-submission-status
    depends_on:
      redis:
        condition: service_healthy
      dind:
        condition: service_healthy
    networks:
      - backend
      - execution
      - redis_network

  auth-service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    # ports:
    #   - 3002:3002
    restart: unless-stopped
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=auth_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_ACCESS_SECRET=ldfjsdfkEKFHWK#&!#*81273
      - JWT_REFRESH_SECRET=ldfjsdfkEKFHWK#&!#*81273
      - JWT_ACCESS_EXPIRES_IN=1h
      - JWT_REFRESH_EXPIRES_IN=7d
      - PORT=3002
      - NODE_ENV=production
      - SERVICE_NAME=auth-service
      - REGISTRY_SERVICE_URL=http://registry-service:3001/api/v1
      - REGISTRY_HMAC_SHARED_SECRET=kfsKE(@#*oweiKOQWID23984
      - API_GATEWAY_HMAC_SHARED_SECRET=3049sKKJDIWEO2983023909234
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - backend
      - postgres_db_network

networks:
  backend:        # shared / API layer
    driver: bridge
  execution:      # isolated for dind + evaluation only
    driver: bridge
  mongo_db_network:     # only services that need their DB
    driver: bridge
  postgres_db_network:     # only services that need their DB
    driver: bridge
  redis_network:
    driver: bridge

volumes:
  redis_data:
  postgres_data:
  leetcode_mongo_data: