# FROM node:lts-alpine3.23 AS development

# WORKDIR /auth-service

# COPY package*.json ./

# RUN npm ci

# # Install dev dependencies
# RUN npm install --save-dev nodemon ts-node

# COPY . .

# CMD ["npm", "run", "dev"]

FROM node:lts-alpine3.23 AS development

WORKDIR /leetcode-server/auth-service

COPY package*.json ./

RUN npm ci

# Install dev dependencies
RUN npm install --save-dev nodemon ts-node

COPY . .

CMD ["npm", "run", "dev"]